version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "1m"

networks:
  proxy:
    driver: overlay
    name: proxy

services:

  traefik:
    <<: *default-opts
    image: traefik:1.7-alpine
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080" # traefik dashboard
#      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    command:
      # Use your favourite settings here, but add:
      - --docker
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.network=proxy
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
      - --entryPoints=Name:https Address::443 TLS
      - --entryPoints=Name:http Address::80 # don't force HTTPS
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:${TRAEFIK_HOST:-traefik.example.com}
        - traefik.enable=true
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
