---

- hosts : docker
  tasks:
    - name: Include os-specific variables. base_provision_system
      include_vars: "../group_vars/all.yml"

- import_playbook: roles/docker.yml
  tags: [provision-docker]
