---
###
# Base provision playbook
##

- hosts : all
  gather_facts: false
  tasks:
    - name: Include os-specific variables. base_provision_system
      include_vars: "../group_vars/all.yml"

- import_playbook: roles/bp-proxmox-community.yaml
  tags:
    - provision-proxmox-community

- import_playbook: roles/bp-proxmox-add-group-user.yaml
  tags:
    - provision-proxmox-group-list
    - provision-proxmox-group-add

- import_playbook: roles/bp-addkey.yml
  tags:
    - provision-addkey

- import_playbook: roles/bp-timezone.yaml
  tags:
    - provision-timezone

- import_playbook: roles/bp-docker.yml
  tags:
    - provision-docker

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create the private key file to the Proxmox user
      copy:
        content: '{{ lookup("env", "NEW_USER_TOKEN_SECRET") }}'
        dest: '{{ lookup("env", "HOME") }}/.ssh/ansible_{{ lookup("env", "NEW_USER_NAME_LINUX") }}'

# ADD YOUR CUSTOM PROVISIONING PLAYBOOKS HERE
