###
# ansible-galaxy requirements
##
# Automatically installed before each T.A.D.S. Ansible command
##

- src: geerlingguy.pip
#  version: 3.1.0 #2.0.0

- src: geerlingguy.docker
#  version: 7.4.7 #3.1.1
