
.. _`Util2DevOps`: https://github.com/alainivars/utils2devops
.. _`Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`Drf-microservice`: https://github.com/alainivars/drf-microservice
.. _`Issue Util2DevOps`: https://github.com/alainivars/utils2devops/issues
.. _`Readthedoc`: https://utils2devops.readthedocs.io/en/latest/
.. _`Github`: https://github.com/alainivars/utils2devops
.. _`Releases notes`: https://github.com/alainivars/utils2devops/blob/master/docs/releases_notes.rst
.. _`AWS Tools`: https://aws.amazon.com/tools/
.. _`GPC Tools`: https://cloud.google.com/sdk/docs/
.. _`Docker`: https://docs.docker.com/get-started/
.. _`Traefik`: https://traefik.io/
.. _`Portainer`: https://www.portainer.io/installation/
.. _`Terraform`: https://www.terraform.io/downloads.html
