
.. _`Util2DevOps`: https://github.com/alainivars/utils2devops
.. _`Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`Drf-microservice`: https://github.com/alainivars/drf-microservice
.. _`Issue Util2DevOps`: https://github.com/alainivars/utils2devops/issues
.. _`Readthedoc`: https://utils2devops.readthedocs.io/en/latest/
.. _`Github`: https://github.com/alainivars/utils2devops
.. _`Releases notes`: https://github.com/alainivars/utils2devops/blob/master/docs/releases_notes.rst
.. _`AWS Tools`: https://aws.amazon.com/tools/
.. _`AWS Cloud`: https://aws.amazon.com/
.. _`GPC Tools`: https://cloud.google.com/sdk/docs/
.. _`GPC Cloud`: https://cloud.google.com/
.. _`Docker`: https://docs.docker.com/get-started/
.. _`Traefik`: https://traefik.io/
.. _`Ansible`: https://docs.ansible.com/ansible/latest
.. _`Portainer`: https://www.portainer.io/installation/
.. _`Terraform`: https://www.terraform.io/downloads.html
.. _`Elk`: https://www.elastic.co/elk-stack
.. _`OpenFaaS`: https://github.com/openfaas/faas
.. _`Consul`: https://github.com/hashicorp/consul
.. _`Etcd`: https://github.com/etcd-io/etcd
.. _`Icinga2`: https://icinga.com/
.. _`plugin logs`: https://icinga.com/docs/icinga2/latest/doc/13-addons/
